# Generated by Django 4.0.4 on 2022-04-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo_usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='des_email',
        ),
    ]
