# Generated by Django 4.0.4 on 2022-04-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo_usuarios_app', '0002_remove_perfil_des_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontocoleta',
            name='cod_endereco',
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='des_bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='des_cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='des_complemento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='des_estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='des_nome_local',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='des_nome_rua_av',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='des_numero',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
