# Generated by Django 4.0.4 on 2022-04-24 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_endereco', models.CharField(max_length=200)),
                ('dat_dia', models.DateField()),
                ('des_hora', models.TimeField()),
                ('bool_confirmado', models.BooleanField(blank=True)),
                ('des_status_atual_atendimento', models.CharField(choices=[('0', 'Aguardando Confirmação de Atendimento'), ('1', 'Confirmado Atendimento'), ('2', 'Aguardando Confirmação de Doação'), ('3', 'Cancelado'), ('4', 'Concluído')], max_length=1)),
                ('des_obs_beneficiario', models.TextField(blank=True, max_length=300)),
                ('num_pontos_doacao', models.FloatField(default=0)),
                ('dat_criacao', models.DateTimeField(auto_now_add=True)),
                ('dat_alteracao', models.DateTimeField(blank=True, null=True)),
                ('tipo_atendimento', models.BooleanField(blank=True)),
                ('cod_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario', to=settings.AUTH_USER_MODEL)),
                ('cod_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('atendimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ciclo_doacao_app.atendimento')),
                ('bool_confirmado_doacao', models.BooleanField(blank=True)),
                ('des_status_atual_doacao', models.CharField(choices=[('0', 'Confirmada'), ('1', 'Precisa Revisar'), ('2', 'Cancelada'), ('3', 'Aguardando Materiais')], max_length=1)),
            ],
            bases=('ciclo_doacao_app.atendimento',),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_nome_material', models.CharField(max_length=100)),
                ('des_tipo_material', models.CharField(max_length=100)),
                ('num_quantidade_kg', models.FloatField()),
                ('num_pontos', models.FloatField()),
                ('cod_doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclo_doacao_app.doacao')),
            ],
        ),
    ]
