# Generated by Django 4.0.4 on 2022-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo_doacao_app', '0002_alter_doacao_des_status_atual_doacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='des_status_atual_doacao',
            field=models.CharField(choices=[('0', 'Aguardando inicio'), ('1', 'Confirmada'), ('2', 'Precisa Revisar'), ('3', 'Cancelada'), ('4', 'Aguardando Materiais')], max_length=1),
        ),
    ]
