# Generated by Django 4.0.4 on 2022-05-01 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciclo_doacao_app', '0003_alter_doacao_des_status_atual_doacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cod_doacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='ciclo_doacao_app.doacao'),
        ),
    ]
