# Generated by Django 4.0.4 on 2022-04-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclo_usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('des_chave', models.CharField(max_length=200)),
                ('bool_usado', models.BooleanField(default=False)),
                ('dat_expiracao', models.DateTimeField()),
                ('des_status', models.CharField(choices=[('A', 'DISPONÍVEL'), ('E', 'EXPIRADO'), ('U', 'INDISPONÍVEL')], max_length=1)),
                ('dat_criacao', models.DateTimeField(auto_now_add=True)),
                ('cod_doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclo_usuarios_app.doador')),
            ],
        ),
    ]
